export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const GET_CURRENT_PAGE = "GET_CURRENT_PAGE";
export const GET_CINEMA_LIST = "GET_CINEMA_LIST";
export const CHOOSE_CINEMA = "CHOOSE_CINEMA";
export const GET_CINEMA_SCHEDULE = "GET_CINEMA_SCHEDULE";
export const SET_TOKEN = "SET_TOKEN";
export const GET_ID_CINEMA_SYSTEM = "GET_ID_CINEMA_SYSTEM";
export const GET_ID_CINEMA = "GET_ID_CINEMA";
export const GET_ADDRESS_CINEMA = "GET_ADDRESS_CINEMA";
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const REMOVE_CREDENTIALS = "REMOVE_CREDENTIALS";
export const GET_CURRENT_WEB_PAGE = "GET_CURRENT_WEB_PAGE";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_CINEMA_INFO = "GET_CINEMA_INFO";
export const GET_CINEMA_TIME = "GET_CINEMA_TIME";
export const SET_DATE = "SET_DATE";
export const GET_MOVIE_DETAIL_SCHEDULE = "GET_MOVIE_DETAIL_SCHEDULE";
export const GET_BOOKING_LIST = "GET_BOOKING_LIST";
export const CHOOSE_SEAT = "CHOOSE_SEAT";
export const CLEAR_SEAT = "CLEAR_SEAT";
export const GET_ALL_MOVIE = "GET_ALL_MOVIE";

export const GET_QUICK_SEARCH_MOVIE = "GET_QUICK_SEARCH_MOVIE";
export const GET_SEARCH_MOVIE = "GET_SEARCH_MOVIE";
export const GET_SEARCH_CINEMA = "GET_SEARCH_CINEMA";
export const GET_SEARCH_DATE = "GET_SEARCH_DATE";
export const GET_SEARCH_SHOW_TIME = "GET_SEARCH_SHOW_TIME";
export const GET_MOVIE_SHOW_TIME = "GET_MOVIE_SHOW_TIME";
export const GET_ALL_CINEMA_SHOW_TIME = "GET_ALL_CINEMA_SHOW_TIME";

export const GET_SELECTED_DATE = "GET_SELECTED_DATE";
export const GET_DATE_LIST = "GET_DATE_LIST";
export const GET_FROM_DATE = "GET_FROM_DATE";
export const GET_TO_DATE = "GET_DATE_LIST";

export const RESET_STATE = "RESET_STATE";

export const GET_ACCOUNT_TYPES = "GET_ACCOUNT_TYPES";
export const GET_ACCOUNT_INFO = "GET_ACCOUNT_INFO";
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const CHANGE_USER = "CHANGE_USER";
export const CHANGE_MOVIE = "CHANGE_MOVIE";
