export const GET_COURSE_LIST = 'GET_COURSE_LIST';
export const GET_CURRENT_PAGE = 'GET_CURRENT_PAGE';
export const GET_CINEMA_LIST = 'GET_CINEMA_LIST';
export const GET_CINEMA_DETAIL = 'GET_CINEMA_DETAIL';
export const CHOOSE_CINEMA = 'CHOOSE_CINEMA';
export const GET_CINEMA_SCHEDULE = 'GET_CINEMA_SCHEDULE';
export const SET_TOKEN = 'SET_TOKEN';
export const GET_ID_CINEMA = 'GET_ID_CINEMA'