export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_CINEMA_LIST = "GET_CINEMA_LIST";
export const GET_CINEMA_DETAIL = "GET_CINEMA_DETAIL";
export const CHOOSE_CINEMA = "CHOOSE_CINEMA";
export const GET_CINEMA_SCHEDULE = "GET_CINEMA_SCHEDULE";
export const SET_TOKEN = "SET_TOKEN";
