import React from "react";
import PropTypes from "prop-types";
import { Grid } from "@material-ui/core";
import Letter from "../Alphabet";
import Seat from "../Seat";
import { useSelector } from "react-redux";

const SeatList = () => {
  const list = useSelector(state => state.booking.danhSachGhe)
  let rowIndex = 0;

  const RenderSeats = (type, currentRow = 0) => {
    return list
      .filter((seat) => seat.loaiGhe === type)
      .map((seat, index) => {
        if (index % 11 === 0) {
          rowIndex++;
          return (
            <>
              <Grid key={index} item xs={1}>
                <Letter index={index / 11 + currentRow} />
              </Grid>
              <Grid key={seat.maGhe} item xs={1}>
                <Seat
                seat = {seat}
                  type={type}
                  seatNumber={seat.tenGhe}
                  reserved={seat.daDat}
                />
              </Grid>
            </>
          );
        }

        return (
          <>
            <Grid key={seat.maGhe} item xs={1}>
              <Seat
                seat = {seat}
                type={type}
                seatNumber={seat.tenGhe}
                reserved={seat.daDat}
              />
            </Grid>
          </>
        );
      });
  };

  return (
    <Grid container>
      <Grid item xs={11}>
        <Grid container>{RenderSeats("Thuong")}</Grid>
        <Grid container>{RenderSeats("Vip", rowIndex)}</Grid>
      </Grid>
      <Grid item xs={1}></Grid>
    </Grid>
  );
};

// SeatList.propTypes = {
//   list: PropTypes.array,
// };

// SeatList.defaultProps = {
//   list: [
//     {
//       maGhe: 47561,
//       tenGhe: "01",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "01",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47562,
//       tenGhe: "02",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "02",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47563,
//       tenGhe: "03",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "03",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47564,
//       tenGhe: "04",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "04",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47565,
//       tenGhe: "05",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "05",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47566,
//       tenGhe: "06",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "06",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47567,
//       tenGhe: "07",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "07",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47568,
//       tenGhe: "08",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "08",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47569,
//       tenGhe: "09",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "09",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47570,
//       tenGhe: "10",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "10",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47571,
//       tenGhe: "11",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "11",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47572,
//       tenGhe: "12",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "12",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47573,
//       tenGhe: "13",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "13",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47574,
//       tenGhe: "14",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "14",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47575,
//       tenGhe: "15",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "15",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47576,
//       tenGhe: "16",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "16",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47577,
//       tenGhe: "17",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "17",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47578,
//       tenGhe: "18",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "18",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47579,
//       tenGhe: "19",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "19",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47580,
//       tenGhe: "20",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "20",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47581,
//       tenGhe: "21",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "21",
//       giaVe: 75000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47582,
//       tenGhe: "22",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "22",
//       giaVe: 75000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47583,
//       tenGhe: "23",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "23",
//       giaVe: 75000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47584,
//       tenGhe: "24",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "24",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47585,
//       tenGhe: "25",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "25",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47586,
//       tenGhe: "26",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "26",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47587,
//       tenGhe: "27",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "27",
//       giaVe: 75000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47588,
//       tenGhe: "28",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "28",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47589,
//       tenGhe: "29",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "29",
//       giaVe: 75000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47590,
//       tenGhe: "30",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "30",
//       giaVe: 75000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47591,
//       tenGhe: "31",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "31",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47592,
//       tenGhe: "32",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "32",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47593,
//       tenGhe: "33",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "33",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47594,
//       tenGhe: "34",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "34",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47595,
//       tenGhe: "35",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "35",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47596,
//       tenGhe: "36",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "36",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47597,
//       tenGhe: "37",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "37",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47598,
//       tenGhe: "38",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "38",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47599,
//       tenGhe: "39",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "39",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47600,
//       tenGhe: "40",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "40",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47601,
//       tenGhe: "41",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "41",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47602,
//       tenGhe: "42",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "42",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47603,
//       tenGhe: "43",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "43",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47604,
//       tenGhe: "44",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "44",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47605,
//       tenGhe: "45",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "45",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47606,
//       tenGhe: "46",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "46",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47607,
//       tenGhe: "47",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "47",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47608,
//       tenGhe: "48",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "48",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47609,
//       tenGhe: "49",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "49",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47610,
//       tenGhe: "50",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "50",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47611,
//       tenGhe: "51",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "51",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47612,
//       tenGhe: "52",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "52",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47613,
//       tenGhe: "53",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "53",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47614,
//       tenGhe: "54",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "54",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47615,
//       tenGhe: "55",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "55",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47616,
//       tenGhe: "56",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "56",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47617,
//       tenGhe: "57",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "57",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47618,
//       tenGhe: "58",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "58",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47619,
//       tenGhe: "59",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "59",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47620,
//       tenGhe: "60",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "60",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47621,
//       tenGhe: "61",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "61",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47622,
//       tenGhe: "62",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "62",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47623,
//       tenGhe: "63",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "63",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47624,
//       tenGhe: "64",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "64",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47625,
//       tenGhe: "65",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "65",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47626,
//       tenGhe: "66",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "66",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47627,
//       tenGhe: "67",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "67",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47628,
//       tenGhe: "68",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "68",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47629,
//       tenGhe: "69",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "69",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47630,
//       tenGhe: "70",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "70",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47631,
//       tenGhe: "71",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "71",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47632,
//       tenGhe: "72",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "72",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47633,
//       tenGhe: "73",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "73",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47634,
//       tenGhe: "74",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "74",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47635,
//       tenGhe: "75",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "75",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47636,
//       tenGhe: "76",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "76",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47637,
//       tenGhe: "77",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "77",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47638,
//       tenGhe: "78",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "78",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47639,
//       tenGhe: "79",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "79",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47640,
//       tenGhe: "80",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "80",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47641,
//       tenGhe: "81",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "81",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47642,
//       tenGhe: "82",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "82",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47643,
//       tenGhe: "83",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "83",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47644,
//       tenGhe: "84",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "84",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47645,
//       tenGhe: "85",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "85",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47646,
//       tenGhe: "86",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "86",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47647,
//       tenGhe: "87",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "87",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47648,
//       tenGhe: "88",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "88",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47649,
//       tenGhe: "89",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "89",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47650,
//       tenGhe: "90",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "90",
//       giaVe: 90000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47651,
//       tenGhe: "91",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "91",
//       giaVe: 90000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47652,
//       tenGhe: "92",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "92",
//       giaVe: 90000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47653,
//       tenGhe: "93",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "93",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47654,
//       tenGhe: "94",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "94",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47655,
//       tenGhe: "95",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "95",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47656,
//       tenGhe: "96",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "96",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47657,
//       tenGhe: "97",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "97",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47658,
//       tenGhe: "98",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "98",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47659,
//       tenGhe: "99",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "99",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47660,
//       tenGhe: "100",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "100",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47661,
//       tenGhe: "101",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "101",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47662,
//       tenGhe: "102",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "102",
//       giaVe: 90000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47663,
//       tenGhe: "103",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "103",
//       giaVe: 90000,
//       daDat: true,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47664,
//       tenGhe: "104",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "104",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47665,
//       tenGhe: "105",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "105",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47666,
//       tenGhe: "106",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "106",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47667,
//       tenGhe: "107",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "107",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47668,
//       tenGhe: "108",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "108",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47669,
//       tenGhe: "109",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "109",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47670,
//       tenGhe: "110",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "110",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47671,
//       tenGhe: "111",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "111",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47672,
//       tenGhe: "112",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "112",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47673,
//       tenGhe: "113",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "113",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47674,
//       tenGhe: "114",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "114",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47675,
//       tenGhe: "115",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "115",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47676,
//       tenGhe: "116",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "116",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47677,
//       tenGhe: "117",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "117",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47678,
//       tenGhe: "118",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "118",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47679,
//       tenGhe: "119",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "119",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47680,
//       tenGhe: "120",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "120",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47681,
//       tenGhe: "121",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "121",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47682,
//       tenGhe: "122",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "122",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47683,
//       tenGhe: "123",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "123",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47684,
//       tenGhe: "124",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "124",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47685,
//       tenGhe: "125",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "125",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47686,
//       tenGhe: "126",
//       maRap: 452,
//       loaiGhe: "Vip",
//       stt: "126",
//       giaVe: 90000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47687,
//       tenGhe: "127",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "127",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47688,
//       tenGhe: "128",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "128",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47689,
//       tenGhe: "129",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "129",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47690,
//       tenGhe: "130",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "130",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47691,
//       tenGhe: "131",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "131",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47692,
//       tenGhe: "132",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "132",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47693,
//       tenGhe: "133",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "133",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47694,
//       tenGhe: "134",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "134",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//     {
//       maGhe: 47695,
//       tenGhe: "135",
//       maRap: 452,
//       loaiGhe: "Thuong",
//       stt: "135",
//       giaVe: 75000,
//       daDat: false,
//       taiKhoanNguoiDat: null,
//     },
//   ],
// };

export default SeatList;
