import { Box, Button, ButtonGroup, Grid, Typography } from "@material-ui/core";
import React, { Component } from "react";
import useStyles from "./style";
import List from "@material-ui/core/List";
import ListItem from "@material-ui/core/ListItem";
import ListItemIcon from "@material-ui/core/ListItemIcon";
import Collapse from "@material-ui/core/Collapse";
import ExpandLess from "@material-ui/icons/ExpandLess";
import ExpandMore from "@material-ui/icons/ExpandMore";
import moment from "moment";

//defaultList: data
const defaultList = {
  lichChieu: [
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16099,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16100,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16101,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16102,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16103,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16104,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16105,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16106,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16107,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16108,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16109,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16110,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16111,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16112,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16113,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16114,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16115,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16116,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16117,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16118,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16119,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16120,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16121,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16122,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16123,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16124,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16125,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16126,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16127,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16128,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16129,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16130,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16131,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16132,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16133,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16134,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16135,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16136,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16137,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16138,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16139,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16140,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16141,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16142,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16143,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16144,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16145,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16146,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16147,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16148,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16149,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16150,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16151,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16152,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29917,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29918,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29919,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29920,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29921,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29922,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-01T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29923,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29924,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29925,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29926,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29927,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29928,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-02T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29929,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29930,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29931,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29932,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29933,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29934,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-03T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29935,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29936,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29937,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29938,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29939,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29940,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-04T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29941,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29942,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29943,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29944,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29945,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29946,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-05T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29947,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29948,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29949,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29950,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29951,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29952,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-06T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29953,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29954,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29955,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29956,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29957,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29958,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-07T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29959,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29960,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29961,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29962,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29963,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29964,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-08T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29965,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29966,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29967,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29968,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29969,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 723,
        tenRap: "Rạp 3",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 29970,
      maRap: 723,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-01-09T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40272,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-03-20T02:12:03",
      giaVe: 80000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40277,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2019-05-24T09:30:00",
      giaVe: 80000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40280,
      maRap: 469,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-03-20T05:00:10",
      giaVe: 78900,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40285,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-03-25T06:27:47",
      giaVe: 79800,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 545,
        tenRap: "Rạp 5",
        maCumRap: "cgv-crescent-mall",
        tenCumRap: "CGV - Crescent Mall",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 40286,
      maRap: 545,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-03-27T11:40:37",
      giaVe: 80000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 543,
        tenRap: "Rạp 3",
        maCumRap: "cgv-crescent-mall",
        tenCumRap: "CGV - Crescent Mall",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 40287,
      maRap: 543,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-03-27T12:01:54",
      giaVe: 90000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 739,
        tenRap: "Rạp 9",
        maCumRap: "cns-quoc-thanh",
        tenCumRap: "CNS - Quốc Thanh",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 40291,
      maRap: 739,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-04-04T04:45:18",
      giaVe: 100000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 739,
        tenRap: "Rạp 9",
        maCumRap: "cns-quoc-thanh",
        tenCumRap: "CNS - Quốc Thanh",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 40292,
      maRap: 739,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-04-24T02:18:00",
      giaVe: 100000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 903,
        tenRap: "Rạp 3",
        maCumRap: "megags-cao-thang",
        tenCumRap: "MegaGS - Cao Thắng",
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
      },
      maLichChieu: 40330,
      maRap: 903,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-04-20T05:20:48",
      giaVe: 90000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40498,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-08-31T09:30:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 467,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40503,
      maRap: 467,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-09-17T00:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 451,
        tenRap: "Rạp 1",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40540,
      maRap: 451,
      maPhim: 1314,
      tenPhim: "13 reasons why",
      ngayChieuGioChieu: "2020-10-13T01:56:49",
      giaVe: 80000,
      thoiLuong: 120,
    },
  ],
  maPhim: 1314,
  tenPhim: "13 reasons why",
  biDanh: "13-reasons-why",
  trailer: "https://www.youtube.com/embed/1HpZevFifuo",
  hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/13-reasons-why_gp01.jpg",
  moTa:
    "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.",
  maNhom: "GP01",
  ngayKhoiChieu: "2020-08-28T00:00:00",
  danhGia: 10,
};

//Change data in another form for easier uses
const FilterMovieList = (defaultList) => {
  const list = [
    // {
    //   maHeThongRap: "BHDStar",
    //   cumRap: {
    //     maCumRap: "bhd-star-cineplex-bitexco",
    //      tenCumRap:
    //     ngayChieuGioChieu: ["2019-01-01T10:10:00"],
    //     giaVe: 75000,
    //     thoiLuong: 120,
    //   },
    // },
  ];
  defaultList.lichChieu.forEach((cinema) => {
    let idx = list.findIndex(
      (cinemaInfo) =>
        cinemaInfo.maHeThongRap === cinema.thongTinRap.maHeThongRap
    );
    if (idx !== -1) {
      list[idx].cumRap.ngayChieuGioChieu.push(cinema.ngayChieuGioChieu);
    } else {
      list.push({
        maHeThongRap: cinema.thongTinRap.maHeThongRap,
        cumRap: {
          maCumRap: cinema.thongTinRap.maCumRap,
          tenCumRap: cinema.thongTinRap.tenCumRap,
          ngayChieuGioChieu: [cinema.ngayChieuGioChieu],
          giaVe: cinema.giaVe,
          thoiLuong: cinema.thoiLuong,
        },
      });
    }
  });

  return list;
};

//movieInfo: item in a filtered list
const Time = (movieInfo) => {
  const classes = useStyles();
  console.log(movieInfo);

  return movieInfo.cumRap.ngayChieuGioChieu.map((item, index) => (
    <Grid item xs={3}>
      <Button className={classes.timeBtn} key={index}>
        <div className="time">
          {/* {console.log(item)} */}
          <Typography variant="h6" component="span" className="timeStart">
            {moment(item).format("hh:mm")}
            {/* {console.log(item)} */}
          </Typography>
          <Typography variant="subtitle1" component="span" className="timeEnd">
            ~
            {moment(item)
              .minute(moment(item).minute() + movieInfo.cumRap.thoiLuong)
              .format("hh:mm")}
          </Typography>
        </div>
      </Button>{" "}
    </Grid>
  ));
};

//list: filtered list
//defaultList: data/ props
const RenderShowTime = (list, defaultList) => {
  const classes = useStyles();

  //open/close Collapse
  const [openArr = [], setOpen] = React.useState([]);
  for (let i = 0; i < list.length; i++) {
    let temp = false;
    openArr.push(temp);
  }
  const handleClick = (idx) => {
    let newArr = [...openArr];
    newArr[idx] = !newArr[idx];
    setOpen(newArr);
  };

  return list.map((item, index) => (
    <List
      component="nav"
      aria-labelledby="nested-list-subheader"
      className={classes.root}
      key={index}
    >
      <ListItem button onClick={() => handleClick(index)}>
        <ListItemIcon>
          <img className={classes.img} src={defaultList.hinhAnh} alt="" />
        </ListItemIcon>
        <Typography className={classes.title} component="h6" variant="h6">
          {item.cumRap.tenCumRap}
        </Typography>
        {openArr[index] ? <ExpandLess /> : <ExpandMore />}
      </ListItem>
      <Collapse in={openArr[index]} timeout="auto" unmountOnExit>
        <List component="div" disablePadding>
          <ListItem button className={classes.nested}>
            <Grid container>{Time(item)}</Grid>
          </ListItem>
        </List>
      </Collapse>
    </List>
  ));
};

const ShowTime = (props = defaultList) => {
  const filteredList = FilterMovieList(defaultList);
  return <>{RenderShowTime(filteredList, defaultList)}</>;
};

export default ShowTime;
