import { Box, Button, ButtonGroup, Grid, Typography } from "@material-ui/core";
import React, { Component } from "react";
import useStyles from "./style";
import List from "@material-ui/core/List";
import ListItem from "@material-ui/core/ListItem";
import ListItemIcon from "@material-ui/core/ListItemIcon";
import Collapse from "@material-ui/core/Collapse";
import ExpandLess from "@material-ui/icons/ExpandLess";
import ExpandMore from "@material-ui/icons/ExpandMore";
import moment from "moment";

//defaultList: data
const defaultList = {
  lichChieu: [
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15289,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15290,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15291,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15292,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15293,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15294,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15295,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15296,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15297,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15298,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15299,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15300,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15301,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15302,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15303,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15304,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15305,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15306,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15307,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15308,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15309,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15310,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15311,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15312,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15313,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15314,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15315,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15316,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15317,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15318,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15319,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15320,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15321,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15322,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15323,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15324,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15325,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15326,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15327,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15328,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15329,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15330,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15331,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15332,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15333,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15334,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15335,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15336,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15337,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15338,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15339,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15340,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15341,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 452,
        tenRap: "Rạp 2",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 15342,
      maRap: 452,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29107,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29108,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29109,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29110,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29111,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29112,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-01T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29113,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29114,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29115,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29116,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29117,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29118,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-02T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29119,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29120,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29121,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29122,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29123,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29124,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-03T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29125,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29126,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29127,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29128,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29129,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29130,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-04T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29131,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29132,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29133,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29134,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29135,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29136,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-05T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29137,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29138,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29139,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29140,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29141,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29142,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-06T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29143,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29144,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29145,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29146,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29147,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29148,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-07T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29149,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29150,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29151,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29152,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29153,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29154,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-08T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29155,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29156,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29157,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29158,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29159,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 708,
        tenRap: "Rạp 8",
        maCumRap: "cgv-vincom-thu-duc",
        tenCumRap: "CGV - Vincom Thủ Đức",
        maHeThongRap: "CGV",
        tenHeThongRap: "cgv",
      },
      maLichChieu: 29160,
      maRap: 708,
      maPhim: 1283,
      tenPhim: "Trainwreck",
      ngayChieuGioChieu: "2019-01-09T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
  ],
  maPhim: 1283,
  tenPhim: "Trainwreck",
  biDanh: "trainwreck",
  trailer: "https://www.youtube.com/embed/2MxnhBPoIx4",
  hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/trainwreck.jpg",
  moTa:
    "Having thought that monogamy was never possible, a commitment-phobic career woman may have to face her fears when she meets a good guy.",
  maNhom: "GP00",
  ngayKhoiChieu: "2019-07-29T00:00:00",
  danhGia: 5,
};

//Change data in another form for easier uses
const FilterMovieList = (defaultList) => {
  const list = [
    // {
    //   maHeThongRap: "BHDStar",
    //   cumRap: {
    //     maCumRap: "bhd-star-cineplex-bitexco",
    //      tenCumRap:
    //     ngayChieuGioChieu: ["2019-01-01T10:10:00"],
    //     giaVe: 75000,
    //     thoiLuong: 120,
    //   },
    // },
  ];
  defaultList.lichChieu.forEach((cinema) => {
    let idx = list.findIndex(
      (cinemaInfo) =>
        cinemaInfo.maHeThongRap === cinema.thongTinRap.maHeThongRap
    );
    if (idx !== -1) {
      list[idx].cumRap.ngayChieuGioChieu.push(cinema.ngayChieuGioChieu);
    } else {
      list.push({
        maHeThongRap: cinema.thongTinRap.maHeThongRap,
        cumRap: {
          maCumRap: cinema.thongTinRap.maCumRap,
          tenCumRap: cinema.thongTinRap.tenCumRap,
          ngayChieuGioChieu: [cinema.ngayChieuGioChieu],
          giaVe: cinema.giaVe,
          thoiLuong: cinema.thoiLuong,
        },
      });
    }
  });

  return list;
};

//movieInfo: item in a filtered list
//timeDefault: get time at the moment (Mon, Tue, Wed, etc)
const Time = (
  movieInfo,
  timeDefault = moment("01/07/2019").format("DD/MM/YYYY")
) => {
  const classes = useStyles();
  // console.log(timeDefault);
  return movieInfo.cumRap.ngayChieuGioChieu
    .filter((item) => moment(item).format("DD/MM/YYYY") === timeDefault)
    .map((item, index) => (
      <Grid item xs={6} sm={3}>
        <Button className={classes.timeBtn} key={index}>
          <div className="time">
            <Typography variant="h6" component="span" className="timeStart">
              {moment(item).format("hh:mm")}
            </Typography>
            <Typography
              variant="subtitle1"
              component="span"
              className="timeEnd"
            >
              ~
              {moment(item)
                .minute(moment(item).minute() + movieInfo.cumRap.thoiLuong)
                .format("hh:mm")}
            </Typography>
          </div>
        </Button>
      </Grid>
    ));
};

//list: filtered list
//defaultList: data/ props
//id: maHeThongRap
const RenderShowTime = (list, defaultList, id) => {
  const classes = useStyles();

  //open/close Collapse
  const [openArr = [], setOpen] = React.useState([]);
  for (let i = 0; i < list.length; i++) {
    let temp = false;
    openArr.push(temp);
  }
  const handleClick = (idx) => {
    let newArr = [...openArr];
    newArr[idx] = !newArr[idx];
    setOpen(newArr);
  };

  return list.map((item, index) => {
    if (item.maHeThongRap === id)
      return (
        <List
          component="nav"
          aria-labelledby="nested-list-subheader"
          className={classes.root}
          key={index}
        >
          <ListItem button onClick={() => handleClick(index)}>
            <ListItemIcon>
              <img className={classes.img} src={defaultList.hinhAnh} alt="" />
            </ListItemIcon>
            <Typography className={classes.title} component="h6" variant="h6">
              {item.cumRap.tenCumRap}
            </Typography>
            {openArr[index] ? <ExpandLess /> : <ExpandMore />}
          </ListItem>
          <Collapse in={openArr[index]} timeout="auto" unmountOnExit>
            <List component="div" disablePadding>
              <ListItem button className={classes.nested}>
                <Grid container>{Time(item)}</Grid>
              </ListItem>
            </List>
          </Collapse>
        </List>
      );
  });
};

const ShowTime = (props = defaultList) => {
  const filteredList = FilterMovieList(defaultList);
  return <>{RenderShowTime(filteredList, defaultList, "BHDStar")}</>;
};

export default ShowTime;
