import { Box, Button, ButtonGroup, Grid, Typography } from "@material-ui/core";
import React, { Component } from "react";
import useStyles from "./style";
import List from "@material-ui/core/List";
import ListItem from "@material-ui/core/ListItem";
import ListItemIcon from "@material-ui/core/ListItemIcon";
import Collapse from "@material-ui/core/Collapse";
import ExpandLess from "@material-ui/icons/ExpandLess";
import ExpandMore from "@material-ui/icons/ExpandMore";
import moment from "moment";

//defaultList: data
const defaultList = {
  lichChieu: [
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16207,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16208,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16209,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16210,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16211,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16212,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16213,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16214,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16215,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16216,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16217,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16218,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16219,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16220,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16221,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16222,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16223,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16224,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16225,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16226,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16227,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16228,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16229,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16230,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16231,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16232,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16233,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16234,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16235,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16236,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16237,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16238,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16239,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16240,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16241,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16242,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16243,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16244,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16245,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16246,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16247,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16248,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16249,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16250,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16251,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16252,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16253,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16254,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16255,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16256,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16257,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16258,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16259,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 469,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-bitexco",
        tenCumRap: "BHD Star Cineplex - Bitexco",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 16260,
      maRap: 469,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30025,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30026,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30027,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30028,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30029,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30030,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-01T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30031,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30032,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30033,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30034,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30035,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30036,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-02T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30037,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30038,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30039,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30040,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30041,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30042,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-03T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30043,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30044,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30045,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30046,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30047,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30048,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-04T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30049,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30050,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30051,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30052,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30053,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30054,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-05T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30055,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30056,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30057,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30058,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30059,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30060,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-06T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30061,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30062,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30063,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30064,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30065,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30066,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-07T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30067,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30068,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30069,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30070,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30071,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30072,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-08T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30073,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T10:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30074,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T12:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30075,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T14:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30076,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T16:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30077,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T18:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 725,
        tenRap: "Rạp 5",
        maCumRap: "cns-hai-ba-trung",
        tenCumRap: "CNS - Hai Bà Trưng",
        maHeThongRap: "CineStar",
        tenHeThongRap: "CineStar",
      },
      maLichChieu: 30078,
      maRap: 725,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-01-09T20:10:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 483,
        tenRap: "Rạp 3",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40110,
      maRap: 483,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-21T10:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 481,
        tenRap: "Rạp 1",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40111,
      maRap: 481,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-21T10:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 901,
        tenRap: "Rạp 1",
        maCumRap: "megags-cao-thang",
        tenCumRap: "MegaGS - Cao Thắng",
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
      },
      maLichChieu: 40134,
      maRap: 901,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-26T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 905,
        tenRap: "Rạp 5",
        maCumRap: "megags-cao-thang",
        tenCumRap: "MegaGS - Cao Thắng",
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
      },
      maLichChieu: 40135,
      maRap: 905,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-26T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 903,
        tenRap: "Rạp 3",
        maCumRap: "megags-cao-thang",
        tenCumRap: "MegaGS - Cao Thắng",
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
      },
      maLichChieu: 40136,
      maRap: 903,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-26T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 907,
        tenRap: "Rạp 7",
        maCumRap: "megags-cao-thang",
        tenCumRap: "MegaGS - Cao Thắng",
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
      },
      maLichChieu: 40137,
      maRap: 907,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-26T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 909,
        tenRap: "Rạp 9",
        maCumRap: "megags-cao-thang",
        tenCumRap: "MegaGS - Cao Thắng",
        maHeThongRap: "MegaGS",
        tenHeThongRap: "MegaGS",
      },
      maLichChieu: 40138,
      maRap: 909,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-26T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 489,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40174,
      maRap: 489,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 483,
        tenRap: "Rạp 3",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40175,
      maRap: 483,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 481,
        tenRap: "Rạp 1",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40176,
      maRap: 481,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 487,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40177,
      maRap: 487,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 497,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40178,
      maRap: 497,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 485,
        tenRap: "Rạp 5",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40179,
      maRap: 485,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 499,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40180,
      maRap: 499,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 491,
        tenRap: "Rạp 1",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40181,
      maRap: 491,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 495,
        tenRap: "Rạp 5",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40182,
      maRap: 495,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 493,
        tenRap: "Rạp 3",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40183,
      maRap: 493,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-11-30T12:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 453,
        tenRap: "Rạp 3",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40207,
      maRap: 453,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-08T01:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 451,
        tenRap: "Rạp 1",
        maCumRap: "bhd-star-cineplex-3-2",
        tenCumRap: "BHD Star Cineplex - 3/2",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40208,
      maRap: 451,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-08T01:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 495,
        tenRap: "Rạp 5",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40216,
      maRap: 495,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 481,
        tenRap: "Rạp 1",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40217,
      maRap: 481,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 489,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40218,
      maRap: 489,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 483,
        tenRap: "Rạp 3",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40219,
      maRap: 483,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 487,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40220,
      maRap: 487,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 497,
        tenRap: "Rạp 7",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40221,
      maRap: 497,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 499,
        tenRap: "Rạp 9",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40222,
      maRap: 499,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 491,
        tenRap: "Rạp 1",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40223,
      maRap: 491,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 485,
        tenRap: "Rạp 5",
        maCumRap: "bhd-star-cineplex-vincom-le-van-viet",
        tenCumRap: "BHD Star Cineplex - Vincom Lê Văn Việt",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40224,
      maRap: 485,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
    {
      thongTinRap: {
        maRap: 493,
        tenRap: "Rạp 3",
        maCumRap: "bhd-star-cineplex-vincom-quang-trung",
        tenCumRap: "BHD Star Cineplex - Vincom Quang Trung",
        maHeThongRap: "BHDStar",
        tenHeThongRap: "BHD Star Cineplex",
      },
      maLichChieu: 40225,
      maRap: 493,
      maPhim: 1316,
      tenPhim: "Ted 3",
      ngayChieuGioChieu: "2019-12-12T21:00:00",
      giaVe: 75000,
      thoiLuong: 120,
    },
  ],
  maPhim: 1316,
  tenPhim: "Ted 3",
  biDanh: "ted-3",
  trailer: "https://www.youtube.com/embed/S3AVcCggRnU",
  hinhAnh: "http://movie0706.cybersoft.edu.vn/hinhanh/ted-3_gp03.jpg",
  moTa:
    "Newlywed couple Ted and Tami-Lynn want to have a baby, but in order to qualify to be a parent, Ted will have to prove he's a person in a court of law.",
  maNhom: "GP03",
  ngayKhoiChieu: "2020-10-09T14:08:02.207",
  danhGia: 10,
};


//Change data in another form for easier uses
const FilterMovieList = (defaultList) => {
  const list = [
    // {
    //   maHeThongRap: "BHDStar",
    //   cumRap: {
    //     maCumRap: "bhd-star-cineplex-bitexco",
    //      tenCumRap:
    //     ngayChieuGioChieu: ["2019-01-01T10:10:00"],
    //     giaVe: 75000,
    //     thoiLuong: 120,
    //   },
    // },
  ];
  defaultList.lichChieu.forEach((cinema) => {
    let idx = list.findIndex(
      (cinemaInfo) =>
        cinemaInfo.maHeThongRap === cinema.thongTinRap.maHeThongRap
    );
    if (idx !== -1) {
      list[idx].cumRap.ngayChieuGioChieu.push(cinema.ngayChieuGioChieu);
    } else {
      list.push({
        maHeThongRap: cinema.thongTinRap.maHeThongRap,
        cumRap: {
          maCumRap: cinema.thongTinRap.maCumRap,
          tenCumRap: cinema.thongTinRap.tenCumRap,
          ngayChieuGioChieu: [cinema.ngayChieuGioChieu],
          giaVe: cinema.giaVe,
          thoiLuong: cinema.thoiLuong,
        },
      });
    }
  });

  return list;
};


//movieInfo: item in a filtered list
const Time = (movieInfo) => {
  const classes = useStyles();

  return movieInfo.cumRap.ngayChieuGioChieu.map((item, index) => (
    <Grid item xs={3}>
      <Button className={classes.timeBtn} key={index}>
        <div className="time">
          <Typography variant="h6" component="span" className="timeStart">
            {moment(item).format("hh:mm")}
          </Typography>
          <Typography variant="subtitle1" component="span" className="timeEnd">
            ~
            {moment(item)
              .minute(moment(item).minute() + movieInfo.cumRap.thoiLuong)
              .format("hh:mm")}
          </Typography>
        </div>
      </Button>
    </Grid>
  ));
};

//list: filtered list
//defaultList: data/ props
//id: maHeThongRap
const RenderShowTime = (list, defaultList, id) => {
  const classes = useStyles();

  //open/close Collapse
  const [openArr = [], setOpen] = React.useState([]);
  for (let i = 0; i < list.length; i++) {
    let temp = false;
    openArr.push(temp);
  }
  const handleClick = (idx) => {
    let newArr = [...openArr];
    newArr[idx] = !newArr[idx];
    setOpen(newArr);
  };

  console.log(id);
  return list.map((item, index) => {
    if (item.maHeThongRap === id)
      return (
        <List
          component="nav"
          aria-labelledby="nested-list-subheader"
          className={classes.root}
          key={index}
        >
          <ListItem button onClick={() => handleClick(index)}>
            <ListItemIcon>
              <img className={classes.img} src={defaultList.hinhAnh} alt="" />
            </ListItemIcon>
            <Typography className={classes.title} component="h6" variant="h6">
              {item.cumRap.tenCumRap}
            </Typography>
            {openArr[index] ? <ExpandLess /> : <ExpandMore />}
          </ListItem>
          <Collapse in={openArr[index]} timeout="auto" unmountOnExit>
            <List component="div" disablePadding>
              <ListItem button className={classes.nested}>
                <Grid container>{Time(item)}</Grid>
              </ListItem>
            </List>
          </Collapse>
        </List>
      );
  });
};

const ShowTime = (props = defaultList) => {
  const filteredList = FilterMovieList(defaultList);
  return <>{RenderShowTime(filteredList, defaultList, "BHDStar")}</>;
};

export default ShowTime;
